theme_color:
  primary: brown
  accent: blue

notice:

favicon: /images/favicon.jpg
banner: /images/banner.jpg
avatar: /images/avatar.jpg
rss: /atom.xml

email: 1432440963@qq.com
sns:
  twitter:
  facebook:
  google_plus:
  weibo: https://weibo.com/2360828682/profile
  instagram:
  tumblr:
  github: https://github.com/niemingzhao
  linkedin:
  zhihu: https://www.zhihu.com/people/nie-1-58
  douban:
  qq: tencent://message/?uin=1432440963&Menu=yes
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google: fXjtlIfaDc_X-0P11rO3bEp1Nk4IKXphoJv0GqGZCco
  baidu: I3t1wfwZvd
analytics:
  google_site_id: UA-139531378-1
  baidu_site_id: 1054d51c0b66f1d168829173682c8159
  cnzz_site_id:

pages:
- name: 标签云
  link: /tagcloud
- name: 画廊
  link: /gallery
links:
- name: 我的简历
  link: http://images.niemingzhao.top/my_resume.html

since: 2016
footer_text: " | 鲁ICP备19009266号-1"
license: 本文遵循 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a> 许可协议

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
donate:
- name: 支付宝
  link: /images/alipay.jpg
- name: 微信支付
  link: /images/wechat.jpg
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin
comment:
  use: changyan
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  changyan_app_id: cyubhC2Dq
  changyan_app_key: prod_e4cce65003c5bed049fefcb8a6f09e12
  changyan_sid_type: _id
